{
    'name': 'DIGIMEN',
    'version': '18.0.1.0.0',
    'summary': 'Digitalni menadžer',
    'license': 'LGPL-3',
    'depends': ['project', 'base', 'mail', 'hr', 'auth_signup', 'web', 'crm', 'sale', 'survey', 'portal', 'website', 'me_sh_document_counter', 'sh_document_management'],
    'data': [
        'security/security.xml',
        'security/demo_users.xml',
        'security/request_rules.xml',
        'security/ir.model.access.csv',
        'views/universal_request_views.xml',
        'views/request_type_views.xml',
        'views/code_book_data.xml',
        'views/code_book_proces.xml',
        'views/calendar_view.xml',
        'views/swot_item_kanban.xml',
        'views/gap_analysis_template.xml',
        'views/gap_analysis_template_ciljevi.xml',
        'views/template_plan_views.xml',
        'views/ost_views_and_actions.xml',
        'views/linkbox_views.xml',
        'views/portal_card_view.xml',
        'views/bmc_views_and_actions.xml',
        'views/lc_views_and_actions.xml',
        'views/universal_request_menus.xml',
        
    ],
    'assets': {
        'web.assets_backend': [
            'universal_request_manager/static/src/js/ost_dashboard.js',
            'universal_request_manager/static/src/js/bmc_lc_report.js',
            'universal_request_manager/static/src/css/universal_request.css',
            'universal_request_manager/static/src/xml/ost_dashboard_template.xml',
            'universal_request_manager/static/src/xml/ost_workflow_board.xml',
            'universal_request_manager/static/src/xml/bmc_lc_report_templates.xml',
        ],
        'web.assets_common': [
            'universal_request_manager/static/src/css/universal_request.css',
        ],
        'web.assets_qweb': [
            'universal_request_manager/static/src/xml/ost_dashboard_template.xml',
            'universal_request_manager/static/src/xml/ost_workflow_board.xml',  
        ],
    },
    'installable': True,
    'application': True,
}
